# Generated by Django 2.1.7 on 2019-04-01 03:46

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('user_imgae', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/app/server/media_files'), upload_to=user.models.image_upload_path, verbose_name='User Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
